version: "3.9"
services:
  curator-daemon:
    image: dbranch/curator
    build:
      context: .
      dockerfile: curator/Dockerfile
  ipfs:
    image: dbranch/ipfs
    build:
      context: .
      dockerfile: ipfs/Dockerfile
