FROM golang

WORKDIR /dbranch
RUN wget https://dist.ipfs.io/go-ipfs/v0.12.2/go-ipfs_v0.12.2_linux-amd64.tar.gz
RUN tar -xvzf go-ipfs_v0.12.2_linux-amd64.tar.gz

WORKDIR /dbranch/go-ipfs
RUN sh install.sh

WORKDIR /dbranch
COPY ./ipfs/config.json .
RUN ipfs init
CMD ipfs daemon --enable-pubsub-experiment
